#ifndef CP0_EVDEV_INPUT_H
#define CP0_EVDEV_INPUT_H

#include <array>
#include <cstdint>
#include <vector>

// Reads Linux evdev devices and exposes Libretro-friendly input state.
class EvdevInput {
public:
    // Opens available /dev/input/event* devices and initializes key mappings.
    bool init();

    // Closes all input device descriptors.
    void shutdown();

    // Polls queued evdev events and updates joypad/keyboard state.
    void poll();

    // Returns the current Libretro joypad state for one button id.
    int16_t joypad_state(unsigned id) const;

    // Returns the current keyboard state for one Libretro keycode.
    int16_t keyboard_state(unsigned keycode) const;

    // Runtime input modes used by systems with reduced layouts or keyboard input.
    void set_two_button_mode(bool enabled) { two_button_mode_ = enabled; }
    void set_trigger_alias_mode(bool enabled) { trigger_alias_mode_ = enabled; }
    void set_keyboard_enabled(bool enabled) { keyboard_enabled_ = enabled; }

    // Forwards keyboard events to cores that registered a Libretro keyboard callback.
    void set_keyboard_event_callback(void (*callback)(bool, unsigned, uint32_t, uint16_t))
    {
        keyboard_event_callback_ = callback;
    }

    bool quit_requested() const { return quit_; }

    // Consumes accumulated frontend actions generated by special keys.
    int consume_volume_steps();
    int consume_brightness_steps();
    int consume_return_to_ui_requests();

private:
    void init_key_bindings();
    void handle_keyboard_event(int code, int value);

    std::vector<int> fds_;
    std::array<int, 1024> key_to_joypad_ {};
    std::array<bool, 256> joypad_ {};
    std::array<bool, 512> keyboard_ {};
    bool keyboard_enabled_ = false;
    void (*keyboard_event_callback_)(bool, unsigned, uint32_t, uint16_t) = nullptr;
    bool two_button_mode_ = false;
    bool trigger_alias_mode_ = false;
    bool quit_ = false;
    int volume_steps_ = 0;
    int brightness_steps_ = 0;
    int return_to_ui_requests_ = 0;
    bool volume_up_held_ = false;
    bool volume_down_held_ = false;
    uint64_t volume_up_next_repeat_ms_ = 0;
    uint64_t volume_down_next_repeat_ms_ = 0;
    bool brightness_left_held_ = false;
    bool brightness_right_held_ = false;
    uint64_t brightness_left_next_repeat_ms_ = 0;
    uint64_t brightness_right_next_repeat_ms_ = 0;
};

#endif // CP0_EVDEV_INPUT_H
